version: '3.0'

volumes:
  db_volume:

services :
  db:
    image: mysql:5.7
    restart: always
    container_name: 'db'
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
    volumes:
      - db_volume:/var/lib/mysql

  adminer:
    container_name: 'adminer'
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    container_name: 'web'
    build: ./web
    restart: always
    ports:
      - 80:80
    links:
     - db